  title = "Advanced Analytics for Web"
  theme = "hugo-theme-learn"

[params]
  themesdir = "themes/hugo-theme-learn"
  metaDataFormat = "yaml"
  description = "Advanced Analytics for Web"
  author = "Agnes Kiss and Jack Keene"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = false
  disableSearch = true
  customMermaidURL = "https://unpkg.com/browse/mermaid@8.1.0/dist/mermaid.min.js"
  titleSeparator = "|"
  baseURL = "https://snowplow-incubator.github.io/advanced-analytics-web-accelerator"
  landingPageName = "Introduction" 
  landingPageURL = "/advanced-analytics-web-accelerator/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "Try Snowplow"
identifier = "ds"
url = "https://try.snowplowanalytics.com/"
weight = 10

