landingPageURL = "/advanced-analytics-web-accelerator/en/introduction"
title = "Advanced Analytics for Web"

[params]
description = "Tutorial for setting up advanced analytics on a website"
author = "Agnes Kiss and Jack Keene"
baseURL = "https://docs.snowplow.io/advanced-analytics-web-accelerator/"
