title = "Advanced Analytics for Web"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

baseURL = "https://snowplow-incubator.github.io/advanced-analytics-web-accelerator/"
languageCode = "en-US"
defaultContentLanguage = "en"
landingPageName = "Introduction" 
disableLandingPageButton = true

[params]
  description = "Advanced Analytics for Web"
  author = "Agnes Kiss and Jack Keene"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = false
  disableSearch = true
  customMermaidURL = "https://unpkg.com/browse/mermaid@8.1.0/dist/mermaid.min.js"
  titleSeparator = "|"
  baseURL = "https://snowplow-incubator.github.io/advanced-analytics-web-accelerator/"
  themeVariant = "custom"



[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Advanced Analytics for Web"
titleSeparator = "|"
weight = 1
languageName = "English"
landingPageName = "Introduction" 
landingPageURL = "/advanced-analytics-web-accelerator/"

[Languages.fr]
title = "Advanced Analytics for Web"
titleSeparator = "|"
weight = 1
languageName = "French"
landingPageName = "Introduction" 
landingPageURL = "/advanced-analytics-web-accelerator/"

[[Languages.en.menu.shortcuts]]
name = "Try Snowplow"
identifier = "ds"
url = "https://try.snowplowanalytics.com/"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "Try Snowplow"
identifier = "ds"
url = "https://try.snowplowanalytics.com/"
weight = 10

