title = "Advanced Analytics for Web"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

baseURL = "https://docs.snowplow.io/accelerators/advanced-analytics-web-accelerator/"
languageCode = "en-US"
defaultContentLanguage = "en"
landingPageName = "Introduction"
disableLandingPageButton = true
disableKinds = ["home"]


[params]
  description = "Advanced Analytics for Web"
  author = "Agnes Kiss and Jack Keene"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = true
  disableMermaid = false
  disableSearch = true
  customMermaidURL = "https://unpkg.com/browse/mermaid@8.1.0/dist/mermaid.min.js"
  titleSeparator = "|"
  baseURL = "https://docs.snowplow.io/accelerators/advanced-analytics-web-accelerator/"
  themeVariant = "custom"



[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Advanced Analytics for Web"
titleSeparator = "|"
weight = 1
languageName = "English"
landingPageName = "Introduction"
landingPageURL = "/accelerators/advanced-analytics-web-accelerator/en/introduction/"

[Languages.fr]
title = "Advanced Analytics for Web"
titleSeparator = "|"
weight = 1
languageName = "French"
landingPageName = "Introduction"
landingPageURL = "/advanced-analytics-web-accelerator/"

[[Languages.en.menu.shortcuts]]
name = "Try Snowplow"
identifier = "ts"
url = "https://try.snowplowanalytics.com/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "Book a demo"
identifier = "b"
url = "https://snowplow.io/get-started/book-a-demo-of-snowplow-bdp/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "Documentation"
identifier = "d"
url = "https://docs.snowplow.io/docs/"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
identifier = "g"
url = "https://github.com/snowplow"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "Discourse"
identifier = "di"
url = "https://discourse.snowplow.io/"
weight = 50

[[Languages.fr.menu.shortcuts]]
name = "Try Snowplow"
identifier = "ts"
url = "https://try.snowplowanalytics.com/"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "Book a demo"
identifier = "b"
url = "https://snowplow.io/get-started/book-a-demo-of-snowplow-bdp/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "Documentation"
identifier = "d"
url = "https://docs.snowplow.io/docs/"
weight = 30

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github"
identifier = "g"
url = "https://github.com/snowplow"
weight = 40

[[Languages.fr.menu.shortcuts]]
name = "Discourse"
identifier = "di"
url = "https://discourse.snowplow.io/"
weight = 50
