[build]
publish = 'public'
command = './scripts/build.sh'
[build.environment]
HUGO_VERSION = '0.104.1'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[redirects]]
from = "/en/introduction"
to = "/"
status = 301
