[build]
publish = 'public'
command = './scripts/build.sh'
[build.environment]
HUGO_VERSION = '0.104.1'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
HUGO_BASEURL = 'https://docs.snowplow.io/accelerators/advanced-analytics-web/'

[context.deploy-preview]
command = './scripts/build.sh $DEPLOY_PRIME_URL'

[context.branch-deploy]
command = './scripts/build.sh $DEPLOY_PRIME_URL'
