on: [push]

env:
  HUGO_BASEURL: 'https://snowplow.github.io/advanced-analytics-web-accelerator/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive
    
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          
      - name: Build
        run: ./scripts/build.sh
        
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
